### ISSUE TITLE
Download M3SDA Dataset

### ISSUE THREAD

**Issue by jongchyisu** [VisionLearningGroup/VisionLearningGroup.github.io#2]
Hi, I'm interested in the M3SDA dataset and was trying to download, but there is no link for the clipart and paintings (http://ai.bu.edu/M3SDA/#dataset). Where can I get the dataset? Thank you!

**Comment by xcpeng** [comment]
Hi, we retain the clipart and painting subset as we are going to hold a domain adaptation challenge. These two domains will be used as the testing domain. 
The link to the domain adaptation challenge is:
http://ai.bu.edu/visda-2019/
We will release the clipart and painting subset on 9/1/2019
